/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import modele.dao.DaoVille;
import modele.dao.Jdbc;
import modele.metier.Ville;

/**
 *
 * @author btssio
 */
public class VueChoixVilleApproxDesCPs extends javax.swing.JDialog {

    private Ecouteur ecouteur;          // l'écouteur d'événements
    private DefaultComboBoxModel jComboBoxModelVille;
    private DefaultListModel jListModelCPs; // modèle de la Jlist

    /**
     * Creates new form VueChoixVille
     */
    public VueChoixVilleApproxDesCPs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // instanciation d'un listener
        ecouteur = new Ecouteur(this);
        // ajout du listener au différents contrôles écoutés
        jComboBoxVille.addActionListener(ecouteur);
        jTextFieldCP.addKeyListener(ecouteur);
        jListCPs.addListSelectionListener(ecouteur);
        jButtonAnnuler.addActionListener(ecouteur);
        jButtonValider.addActionListener(ecouteur);

        jComboBoxModelVille = new DefaultComboBoxModel();
        jComboBoxVille.setModel(jComboBoxModelVille);
        jListModelCPs = new DefaultListModel();
        jListCPs.setModel(jListModelCPs);
        jListCPs.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonValider = new javax.swing.JButton();
        jComboBoxVille = new javax.swing.JComboBox();
        jTextFieldCP = new javax.swing.JTextField();
        jLabelListCPs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListCPs = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCPChoisi = new javax.swing.JTextField();
        jButtonAnnuler = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Choix d'une ville");

        jLabel2.setText("Code postal  :");

        jLabel3.setText("Ville :");

        jButtonValider.setText("Valider");

        jComboBoxVille.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));

        jLabelListCPs.setText("CPs de la ville :");

        jScrollPane1.setViewportView(jListCPs);

        jLabel5.setText("CP choisi :");

        jTextFieldCPChoisi.setEnabled(false);

        jButtonAnnuler.setText("Annuler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelListCPs)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxVille, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCPChoisi, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAnnuler)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonValider)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelListCPs)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCPChoisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValider)
                    .addComponent(jButtonAnnuler))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initialisationComboVilles() {
        String unCp = jTextFieldCP.getText().trim();
//        int longueurCp = unCp.length();
//        if (longueurCp < 5) {
//            unCp += '%';
//        }
        Jdbc.creer("oracle.jdbc.driver.OracleDriver", "jdbc:oracle:thin:", "@localhost:1521:XE", "", "btssio", "btssio");

        try {
            Jdbc.getInstance().connecter();
            jComboBoxModelVille = new DefaultComboBoxModel();
            List<Ville> lesVilles = DaoVille.selectAllByCpApprox(unCp, 2, 1);
            for (Ville ville : lesVilles) {
                jComboBoxModelVille.addElement(ville);
            }
            jComboBoxVille.setModel(jComboBoxModelVille);
            jListModelCPs.clear();
            jTextFieldCP.setText(jTextFieldCP.getText().trim());
            if (lesVilles.size() > 0) {
                remplissageListeCps(lesVilles.get(0).getCp());
                if (jTextFieldCP.getText().length() == 5) {
                    jTextFieldCPChoisi.setText(jTextFieldCP.getText());
                } else {
                    jTextFieldCPChoisi.setText((String) jListModelCPs.get(0));
                }
            } else {
                jTextFieldCPChoisi.setText("");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Pilote absent");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Echec de connexion");
        }
    }

    private void remplissageListeCps(String ChaineLesCp) {
        String[] tabLesCp = ChaineLesCp.split("-");
        jListModelCPs.clear();
        for (int i = 0; i < tabLesCp.length; i++) {
            jListModelCPs.addElement(tabLesCp[i]);
        }
        if (tabLesCp.length > 1) {
            jListCPs.setEnabled(true);
        }
        // 
        jTextFieldCPChoisi.setText((String) jListCPs.getModel().getElementAt(0));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueChoixVilleApproxDesCPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueChoixVilleApproxDesCPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueChoixVilleApproxDesCPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueChoixVilleApproxDesCPs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VueChoixVilleApproxDesCPs dialog = new VueChoixVilleApproxDesCPs(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * classe privée Ecouteur d'événements, implémentant les méthodes de
     * l'interface ActionListener, ie la méthode actionPerformed et els méthodes
     * de l'interface KeyListener, ie les méthodes keyTyped, keyPressed et
     * keyReleased
     */
    private class Ecouteur implements ActionListener, KeyListener, ListSelectionListener {
        private VueChoixVilleApproxDesCPs vue;
        
        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == jComboBoxVille) {
                remplissageListeCps(((Ville) jComboBoxVille.getSelectedItem()).getCp());
               jTextFieldCPChoisi.setText(((Ville) jComboBoxVille.getSelectedItem()).getCp());
            } else if (e.getSource() == jButtonValider) {
                if (!jTextFieldCPChoisi.getText().equals("")) {
                    Ville ville = (Ville) jComboBoxVille.getSelectedItem();
                    ((VueAdresse_M5_DesCPs) (this.getVue().getParent())).getjTextFieldCdp().setText(jTextFieldCPChoisi.getText());
                    ((VueAdresse_M5_DesCPs) (this.getVue().getParent())).getjTextFieldVille().setText(ville.getNom());
                    ((VueAdresse_M5_DesCPs) (this.getVue().getParent())).setVilleCourante(ville);
                    this.getVue().dispose();
                } else {
                    JOptionPane.showMessageDialog(this.getVue(), "Vous devez saisir le début d'un code postal existant ou Annuler");
                    this.getVue().jTextFieldCP.requestFocus();
                }
            } else if (e.getSource() == jButtonAnnuler) {
                    this.getVue().dispose();                
            
            }
        }

        @Override
        public void keyTyped(KeyEvent e) {
        }

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyChar() == Event.ENTER) {
                if (!jTextFieldCP.getText().equals("")) {
                    initialisationComboVilles();
                }
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
        }

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (e.getSource() == jListCPs) {
                jTextFieldCPChoisi.setText((String) jListCPs.getSelectedValue());
            }
        }
        
        public VueChoixVilleApproxDesCPs getVue() {
            return vue;
        }

        public void setVue(VueChoixVilleApproxDesCPs vue) {
            this.vue = vue;
        }

        public Ecouteur(VueChoixVilleApproxDesCPs vue) {
            this.vue = vue;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox jComboBoxVille;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelListCPs;
    private javax.swing.JList jListCPs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldCPChoisi;
    // End of variables declaration//GEN-END:variables
}
